 
name: TypeScript Check

on:
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd mobile-app
        npm ci
    
    - name: Run TypeScript check
      run: |
        cd mobile-app
        npx tsc --noEmit